[Variables]
Substitute="":"...","&amp;":"&","&quot;":"'","<![CDATA[":"","]]>":"","&apos;":"'","&lt;":"<"

; ---- Regular Expression taken from the RSS Reader on Enigma

ReguExp="(?siU)<title.*>(.*)</title>.*<link.*>(.*)</link>.*<item.*<title.*>(.*)</title>.*<link.*>(.*)</link>(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)(?(?=.*<item).*<title.*>(.*)</title>.*<link.*>(.*)</link>)"

; ---- Show/Hide Each Feed

Hide1=[!RainmeterHideMeter MeterRSS1Title][!RainmeterHideMeter MeterRSS1Item1][!RainmeterHideMeter MeterRSS1Item2][!RainmeterHideMeter MeterRSS1Item3][!RainmeterHideMeter MeterRSS1Item4][!RainmeterHideMeter MeterRSS1Item5][!RainmeterHideMeter MeterRSS1Item6][!RainmeterHideMeter MeterRSS1Item7][!RainmeterHideMeter MeterRSS1Item8][!RainmeterHideMeter MeterRSS1Item9]

Show1=[!RainmeterShowMeter MeterRSS1Title][!RainmeterShowMeter MeterRSS1Item1][!RainmeterShowMeter MeterRSS1Item2][!RainmeterShowMeter MeterRSS1Item3][!RainmeterShowMeter MeterRSS1Item4][!RainmeterShowMeter MeterRSS1Item5][!RainmeterShowMeter MeterRSS1Item6][!RainmeterShowMeter MeterRSS1Item7][!RainmeterShowMeter MeterRSS1Item8][!RainmeterShowMeter MeterRSS1Item9]

Hide2=[!RainmeterHideMeter MeterRSS2Title][!RainmeterHideMeter MeterRSS2Item1][!RainmeterHideMeter MeterRSS2Item2][!RainmeterHideMeter MeterRSS2Item3][!RainmeterHideMeter MeterRSS2Item4][!RainmeterHideMeter MeterRSS2Item5][!RainmeterHideMeter MeterRSS2Item6][!RainmeterHideMeter MeterRSS2Item7][!RainmeterHideMeter MeterRSS2Item8][!RainmeterHideMeter MeterRSS2Item9]

Show2=[!RainmeterShowMeter MeterRSS2Title][!RainmeterShowMeter MeterRSS2Item1][!RainmeterShowMeter MeterRSS2Item2][!RainmeterShowMeter MeterRSS2Item3][!RainmeterShowMeter MeterRSS2Item4][!RainmeterShowMeter MeterRSS2Item5][!RainmeterShowMeter MeterRSS2Item6][!RainmeterShowMeter MeterRSS2Item7][!RainmeterShowMeter MeterRSS2Item8][!RainmeterShowMeter MeterRSS2Item9]

Hide3=[!RainmeterHideMeter MeterRSS3Title][!RainmeterHideMeter MeterRSS3Item1][!RainmeterHideMeter MeterRSS3Item2][!RainmeterHideMeter MeterRSS3Item3][!RainmeterHideMeter MeterRSS3Item4][!RainmeterHideMeter MeterRSS3Item5][!RainmeterHideMeter MeterRSS3Item6][!RainmeterHideMeter MeterRSS3Item7][!RainmeterHideMeter MeterRSS3Item8][!RainmeterHideMeter MeterRSS3Item9]

Show3=[!RainmeterShowMeter MeterRSS3Title][!RainmeterShowMeter MeterRSS3Item1][!RainmeterShowMeter MeterRSS3Item2][!RainmeterShowMeter MeterRSS3Item3][!RainmeterShowMeter MeterRSS3Item4][!RainmeterShowMeter MeterRSS3Item5][!RainmeterShowMeter MeterRSS3Item6][!RainmeterShowMeter MeterRSS3Item7][!RainmeterShowMeter MeterRSS3Item8][!RainmeterShowMeter MeterRSS3Item9]

Hide4=[!RainmeterHideMeter MeterRSS4Title][!RainmeterHideMeter MeterRSS4Item1][!RainmeterHideMeter MeterRSS4Item2][!RainmeterHideMeter MeterRSS4Item3][!RainmeterHideMeter MeterRSS4Item4][!RainmeterHideMeter MeterRSS4Item5][!RainmeterHideMeter MeterRSS4Item6][!RainmeterHideMeter MeterRSS4Item7][!RainmeterHideMeter MeterRSS4Item8][!RainmeterHideMeter MeterRSS4Item9]

Show4=[!RainmeterShowMeter MeterRSS4Title][!RainmeterShowMeter MeterRSS4Item1][!RainmeterShowMeter MeterRSS4Item2][!RainmeterShowMeter MeterRSS4Item3][!RainmeterShowMeter MeterRSS4Item4][!RainmeterShowMeter MeterRSS4Item5][!RainmeterShowMeter MeterRSS4Item6][!RainmeterShowMeter MeterRSS4Item7][!RainmeterShowMeter MeterRSS4Item8][!RainmeterShowMeter MeterRSS4Item9]

Hide5=[!RainmeterHideMeter MeterRSS5Title][!RainmeterHideMeter MeterRSS5Item1][!RainmeterHideMeter MeterRSS5Item2][!RainmeterHideMeter MeterRSS5Item3][!RainmeterHideMeter MeterRSS5Item4][!RainmeterHideMeter MeterRSS5Item5][!RainmeterHideMeter MeterRSS5Item6][!RainmeterHideMeter MeterRSS5Item7][!RainmeterHideMeter MeterRSS5Item8][!RainmeterHideMeter MeterRSS5Item9]

Show5=[!RainmeterShowMeter MeterRSS5Title][!RainmeterShowMeter MeterRSS5Item1][!RainmeterShowMeter MeterRSS5Item2][!RainmeterShowMeter MeterRSS5Item3][!RainmeterShowMeter MeterRSS5Item4][!RainmeterShowMeter MeterRSS5Item5][!RainmeterShowMeter MeterRSS5Item6][!RainmeterShowMeter MeterRSS5Item7][!RainmeterShowMeter MeterRSS5Item8][!RainmeterShowMeter MeterRSS5Item9]

Hide6=[!RainmeterHideMeter MeterRSS6Title][!RainmeterHideMeter MeterRSS6Item1][!RainmeterHideMeter MeterRSS6Item2][!RainmeterHideMeter MeterRSS6Item3][!RainmeterHideMeter MeterRSS6Item4][!RainmeterHideMeter MeterRSS6Item5][!RainmeterHideMeter MeterRSS6Item6][!RainmeterHideMeter MeterRSS6Item7][!RainmeterHideMeter MeterRSS6Item8][!RainmeterHideMeter MeterRSS6Item9]

Show6=[!RainmeterShowMeter MeterRSS6Title][!RainmeterShowMeter MeterRSS6Item1][!RainmeterShowMeter MeterRSS6Item2][!RainmeterShowMeter MeterRSS6Item3][!RainmeterShowMeter MeterRSS6Item4][!RainmeterShowMeter MeterRSS6Item5][!RainmeterShowMeter MeterRSS6Item6][!RainmeterShowMeter MeterRSS6Item7][!RainmeterShowMeter MeterRSS6Item8][!RainmeterShowMeter MeterRSS6Item9]

Hide7=[!RainmeterHideMeter MeterRSS7Title][!RainmeterHideMeter MeterRSS7Item1][!RainmeterHideMeter MeterRSS7Item2][!RainmeterHideMeter MeterRSS7Item3][!RainmeterHideMeter MeterRSS7Item4][!RainmeterHideMeter MeterRSS7Item5][!RainmeterHideMeter MeterRSS7Item6][!RainmeterHideMeter MeterRSS7Item7][!RainmeterHideMeter MeterRSS7Item8][!RainmeterHideMeter MeterRSS7Item9]

Show7=[!RainmeterShowMeter MeterRSS7Title][!RainmeterShowMeter MeterRSS7Item1][!RainmeterShowMeter MeterRSS7Item2][!RainmeterShowMeter MeterRSS7Item3][!RainmeterShowMeter MeterRSS7Item4][!RainmeterShowMeter MeterRSS7Item5][!RainmeterShowMeter MeterRSS7Item6][!RainmeterShowMeter MeterRSS7Item7][!RainmeterShowMeter MeterRSS7Item8][!RainmeterShowMeter MeterRSS7Item9]

Hide8=[!RainmeterHideMeter MeterRSS8Title][!RainmeterHideMeter MeterRSS8Item1][!RainmeterHideMeter MeterRSS8Item2][!RainmeterHideMeter MeterRSS8Item3][!RainmeterHideMeter MeterRSS8Item4][!RainmeterHideMeter MeterRSS8Item5][!RainmeterHideMeter MeterRSS8Item6][!RainmeterHideMeter MeterRSS8Item7][!RainmeterHideMeter MeterRSS8Item8][!RainmeterHideMeter MeterRSS8Item9]

Show8=[!RainmeterShowMeter MeterRSS8Title][!RainmeterShowMeter MeterRSS8Item1][!RainmeterShowMeter MeterRSS8Item2][!RainmeterShowMeter MeterRSS8Item3][!RainmeterShowMeter MeterRSS8Item4][!RainmeterShowMeter MeterRSS8Item5][!RainmeterShowMeter MeterRSS8Item6][!RainmeterShowMeter MeterRSS8Item7][!RainmeterShowMeter MeterRSS8Item8][!RainmeterShowMeter MeterRSS8Item9]

Hide9=[!RainmeterHideMeter MeterRSS9Title][!RainmeterHideMeter MeterRSS9Item1][!RainmeterHideMeter MeterRSS9Item2][!RainmeterHideMeter MeterRSS9Item3][!RainmeterHideMeter MeterRSS9Item4][!RainmeterHideMeter MeterRSS9Item5][!RainmeterHideMeter MeterRSS9Item6][!RainmeterHideMeter MeterRSS9Item7][!RainmeterHideMeter MeterRSS9Item8][!RainmeterHideMeter MeterRSS9Item9]

Show9=[!RainmeterShowMeter MeterRSS9Title][!RainmeterShowMeter MeterRSS9Item1][!RainmeterShowMeter MeterRSS9Item2][!RainmeterShowMeter MeterRSS9Item3][!RainmeterShowMeter MeterRSS9Item4][!RainmeterShowMeter MeterRSS9Item5][!RainmeterShowMeter MeterRSS9Item6][!RainmeterShowMeter MeterRSS9Item7][!RainmeterShowMeter MeterRSS9Item8][!RainmeterShowMeter MeterRSS9Item9]

Hide10=[!RainmeterHideMeter MeterRSS10Title][!RainmeterHideMeter MeterRSS10Item1][!RainmeterHideMeter MeterRSS10Item2][!RainmeterHideMeter MeterRSS10Item3][!RainmeterHideMeter MeterRSS10Item4][!RainmeterHideMeter MeterRSS10Item5][!RainmeterHideMeter MeterRSS10Item6][!RainmeterHideMeter MeterRSS10Item7][!RainmeterHideMeter MeterRSS10Item8][!RainmeterHideMeter MeterRSS10Item9]

Show10=[!RainmeterShowMeter MeterRSS10Title][!RainmeterShowMeter MeterRSS10Item1][!RainmeterShowMeter MeterRSS10Item2][!RainmeterShowMeter MeterRSS10Item3][!RainmeterShowMeter MeterRSS10Item4][!RainmeterShowMeter MeterRSS10Item5][!RainmeterShowMeter MeterRSS10Item6][!RainmeterShowMeter MeterRSS10Item7][!RainmeterShowMeter MeterRSS10Item8][!RainmeterShowMeter MeterRSS10Item9]

; ---- Show/Hide Rest

HideRest=[!RainmeterHideMeter Background][!RainmeterHideMeter DIVIDER1][!RainmeterHideMeter DIVIDER2][!RainmeterHideMeter RSSImage1][!RainmeterHideMeter MeterShowFeed1][!RainmeterHideMeter MeterShowFeed2][!RainmeterHideMeter MeterShowFeed3][!RainmeterHideMeter MeterShowFeed4][!RainmeterHideMeter MeterShowFeed5][!RainmeterHideMeter MeterShowFeed6][!RainmeterHideMeter MeterShowFeed7][!RainmeterHideMeter MeterShowFeed8][!RainmeterHideMeter MeterShowFeed9][!RainmeterHideMeter MeterShowFeed10]

ShowRest=[!RainmeterShowMeter Background][!RainmeterShowMeter DIVIDER1][!RainmeterShowMeter DIVIDER2][!RainmeterShowMeter RSSImage1][!RainmeterShowMeter MeterShowFeed1][!RainmeterShowMeter MeterShowFeed2][!RainmeterShowMeter MeterShowFeed3][!RainmeterShowMeter MeterShowFeed4][!RainmeterShowMeter MeterShowFeed5][!RainmeterShowMeter MeterShowFeed6][!RainmeterShowMeter MeterShowFeed7][!RainmeterShowMeter MeterShowFeed8][!RainmeterShowMeter MeterShowFeed9][!RainmeterShowMeter MeterShowFeed10]